project:
  type: website
  output-dir: docs

website:
  reader-mode: false
  back-to-top-navigation: true
  title: "EM Del Ponte"
  page-navigation: true
  open-graph: true
  twitter-card: true
  
  page-footer: 
    background: light
    left: Â© Emerson Del Ponte
    right: This website is built with [Quarto](https://quarto.org/){target=_blank}
  navbar:
    collapse-below: lg
    search: true
    left:
      - icon: house
        href: index.qmd
        text: Home

      - icon: people
        href: about.qmd
        text: About me

      - icon: people
        href: lab.qmd
        text: The lab

      - icon: tools
        href: apps.qmd
        text: Resources

      - icon: pen
        href: posts.qmd
        text: Posts

      - text: Risk maps
        icon: map
        menu:
          - text: Brusone do trigo
            href: brusone.qmd
            icon: map
          - text: Ferrugem da soja
            href: ferrugemsoja.qmd
            icon: map


    right:
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/edelponte.bsky.social
        aria-label: My bluesky
      - icon: github
        href: https://github.com/emdelponte
        aria-label: My GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/emerson-m-del-ponte-61678ba1/
        aria-label: My Linkedin

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    




